In [35]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [36]:
import tensorflow as tf

2.6.0


tensorflow.python.framework.ops.EagerTensor

In [40]:
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow!'>

In [41]:
print(hello)

tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


In [42]:
x = tf.constant(10)

In [43]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [32]:
import tensorflow as tf
print(tf.__version__)

# Construct a `Session` to execute the graph.
with tf.compat.v1.Session() as sess:

  # Build a dataflow graph.
  c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
  d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
  e = tf.matmul(c, d)

  # Execute the graph and store the value that `e` represents in `result`.
  result = sess.run(e)
  print(result)

2.6.0
[[1. 3.]
 [3. 7.]]


In [44]:
# running sessions
with tf.compat.v1.Session() as sess:
    hello = tf.constant('Hello, TensorFlow!')

    
    result = sess.run(hello)
    print(result)

b'Hello, TensorFlow!'


In [34]:
type(result)

bytes

In [49]:
tf.compat.v1.disable_eager_execution() # added line to avoid error

In [50]:
# operations
x = tf.constant(10)
y = tf.constant(2)

In [51]:
with tf.compat.v1.Session() as sess:
    print('Operations and Constants')
    print('Addition', sess.run(x + y))
    print('Subtraction', sess.run(x - y))
    print('Multiplication', sess.run(x * y))
    print('Division', sess.run(x / y))

Operations and Constants
Addition 12
Subtraction 8
Multiplication 20
Division 5.0


In [52]:
# placeholders
x = tf.compat.v1.placeholder(tf.float32)
y = tf.compat.v1.placeholder(tf.float32)

In [53]:
x

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [54]:
type(x)

tensorflow.python.framework.ops.Tensor

In [55]:
# running operations with variable input:
d = {x: 20, y: 30}

with tf.compat.v1.Session() as sess:
    print('Operations and Placeholders')
    print('Addition', sess.run(x + y, feed_dict=d))
    print('Subtraction', sess.run(x - y, feed_dict=d))
    print('Multiplication', sess.run(x * y, feed_dict=d))
    print('Division', sess.run(x / y, feed_dict=d))

Operations and Placeholders
Addition 50.0
Subtraction -10.0
Multiplication 600.0
Division 0.6666667


In [56]:
import numpy as np

In [57]:
# using matrix multiplication
a = np.array([[5.0, 5.0]])
b = np.array([[2.0], [2.0]])

In [58]:
a

array([[5., 5.]])

In [59]:
b

array([[2.],
       [2.]])

In [60]:
a.shape

(1, 2)

In [61]:
b.shape

(2, 1)

In [62]:
mat1 = tf.constant(a)

In [63]:
mat2 = tf.constant(b)

In [64]:
matrix_mult = tf.matmul(mat1, mat2)

In [65]:
with tf.compat.v1.Session() as sess:
    result = sess.run(matrix_mult)
    print('Matrix Multiplication')
    print(result)

Matrix Multiplication
[[20.]]
